language: python
python:
  - "3.9.7"
# command to install dependencies
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - python manage.py migrate
script:
  - black --check .
  - flake8 .
  - coverage run --source="." manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $awskey
  secret_access_key: $awssecretkey
  region: "us-east-1"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-062376667782"

  only_create_app_version: "true"